-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
DO $$ BEGIN
 CREATE TYPE "public"."theme" AS ENUM('light', 'dark', 'boring');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bartu-chat_chats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""bartu-chat_post_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"name" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"userId" varchar(256) NOT NULL,
	"url" varchar(1024) NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bartu-chat_messages" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name ""bartu-chat_messages_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"chat_id" integer NOT NULL,
	"userId" varchar(256) NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"model" varchar(256) NOT NULL,
	"sender" varchar(256) NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bartu-chat_attachments" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name ""bartu-chat_attachments_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"message_id" integer NOT NULL,
	"file_name" varchar(256) NOT NULL,
	"file_type" varchar(256) NOT NULL,
	"file_size" integer NOT NULL,
	"url" varchar(1024) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bartu-chat_subscriptions" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name ""bartu-chat_subscriptions_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"user_id" varchar(256) NOT NULL,
	"status" varchar(256) NOT NULL,
	"standard_credits" integer NOT NULL,
	"max_standard_credits" integer NOT NULL,
	"premium_credits" integer NOT NULL,
	"max_premium_credits" integer NOT NULL,
	"reset_date" timestamp with time zone,
	"last_updated" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bartu-chat_ai_models" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name ""bartu-chat_ai_models_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"display_name" varchar(256) NOT NULL,
	"provider" varchar(256) NOT NULL,
	"input_price" integer DEFAULT 0 NOT NULL,
	"output_price" integer DEFAULT 0 NOT NULL,
	"tags" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"owner" varchar(256) NOT NULL,
	"name" varchar(256) NOT NULL,
	"user_api_id" integer,
	"max_tokens" integer,
	"is_active" varchar(10) DEFAULT 'true' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bartu-chat_users" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"email" varchar(256) NOT NULL,
	"first_name" varchar(256) NOT NULL,
	"last_name" varchar(256) NOT NULL,
	"profile_picture" varchar(1024),
	"theme" "theme" DEFAULT 'light',
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "bartu-chat_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bartu-chat_user_apis" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name ""bartu-chat_user_apis_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"user_id" varchar(256) NOT NULL,
	"name" varchar(256) NOT NULL,
	"provider" varchar(256) NOT NULL,
	"api_key" varchar(512) NOT NULL,
	"api_url" varchar(1024) NOT NULL,
	"is_active" varchar(10) DEFAULT 'true' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "bartu-chat_chats" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "messages_chat_id_idx" ON "bartu-chat_messages" USING btree ("chat_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "attachments_message_id_idx" ON "bartu-chat_attachments" USING btree ("message_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscriptions_user_id_idx" ON "bartu-chat_subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_models_display_name_idx" ON "bartu-chat_ai_models" USING btree ("display_name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_models_owner_idx" ON "bartu-chat_ai_models" USING btree ("owner");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_models_user_api_idx" ON "bartu-chat_ai_models" USING btree ("user_api_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "users_email_idx" ON "bartu-chat_users" USING btree ("email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "users_id_idx" ON "bartu-chat_users" USING btree ("id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_apis_user_api_idx" ON "bartu-chat_user_apis" USING btree ("user_id","id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_apis_user_id_idx" ON "bartu-chat_user_apis" USING btree ("user_id");
*/